# Generated by Django 5.1.3 on 2024-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0003_rename_salario_liquido_folhapagamento_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
