# Generated by Django 5.1.3 on 2024-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0004_alter_folhapagamento_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='mes',
            field=models.DateField(),
        ),
    ]
